name: Amethyst
version: '${project.version}'
main: wtf.casper.amethyst.paper.InternalAmethystPlugin
api-version: 1.13
load: STARTUP
softdepend:
  - PlaceholderAPI
  - Lands
  - GriefPrevention
  - Floodgate
  - Vault
  - CrashClaim
  - RyseInventory
  - AdvancedVanish
  - DeluxeCombat
  - RoseStacker
  - WorldEdit
  - Towny
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot